"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var bird_1 = require("./bird");
var airbus_1 = require("./airbus");
var superman_1 = require("./superman");
var myFlyer;
var mybird;
mybird = new bird_1.bird();
console.log(mybird.land());
console.log(mybird.takeoff());
console.log(mybird.takeoff());
mybird = new airbus_1.airbus();
console.log(mybird.land());
console.log(mybird.takeoff());
console.log(mybird.takeoff());
mybird = new superman_1.superman();
console.log(mybird.land());
console.log(mybird.takeoff());
console.log(mybird.takeoff());
